version: "3.3"

services:
  go_server_dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "2565:2565"
    expose:
      - 2565
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=go-example-db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./pkg/db:/docker-entrypoint-initdb.d
    command: -p 5432
#docker-compose -f docker-compose-dev.yml up --abort-on-container-exit  --exit-code-from go_server_dev
