version: "3.3"

services:
  test_sandbox:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - .:/app
    depends_on:
      - test_db

  test_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=go-example-db
    ports:
      - "5433:5433"
    expose:
      - 5433
    volumes:
      - ./pkg/db:/docker-entrypoint-initdb.d
    command: -p 5433
#docker-compose -f docker-compose-test.yml up --exit-code-from test_sandbox
