FROM golang:1.19-alpine as build-base

WORKDIR /app

COPY . .
# RUN CGO_ENABLED=0 go test -v ./... -cover

RUN go build -o ./out/go-deploy .

# ====================


FROM alpine:3.16.2
COPY --from=build-base /app/out/go-deploy /app/go-deploy
CMD ["/app/go-deploy"]